version: 2

formats:
  - htmlzip
  - pdf
  - epub

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs


sphinx:
  builder: dirhtml
  configuration: docs/conf.py
