name: Link Checker

on:
  push:
  schedule:
    - cron: '0 0 * * *'


jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install project
        run: |
          python -m pip install -U pip wheel
          pip install -r docs-requirements.txt

      - name: linkcheck
        run: make linkcheck
        working-directory: docs
