name: Autodoc

on:
  push:


jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'


      - name: Install project
        run: |
          python -m pip install -U pip wheel
          pip install -r docs-requirements.txt

      - name: git status of make api
        working-directory: docs
        run: |
          make api
          [ -z "$(git status -s)" ]
