name: Tox

on:
  push:

jobs:
  tox:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        python: ["3.7", "3.8", "3.9", "3.10"]
    runs-on: ${{ matrix.os }}
    name: Tox on ${{ matrix.os }} and python ${{ matrix.python }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install tox
        run: |
          python -m pip install -U pip wheel
          pip install tox

      - name: Run tox
        run: TOXENV="py$(echo "${{ matrix.python }}" | tr -d '.')" tox
